(()=>{const{schedule,stops,routes}=VDC_DATA;
const names={D:'Circular Direto',I:'Circular Inverso',ER:'Expresso Reitoria',ECT:'Expresso C&T',S:'Circular de sábado'};
const colors={D:'#2b7331',I:'#6a1b9a',ER:'#ed7600',ECT:'#1976d2',S:'#2b7331'};
const soft={D:'#edf6ee',I:'#f3ebf7',ER:'#fff0df',ECT:'#e9f3ff',S:'#edf6ee'};
const softDark={D:'#1d2b21',I:'#2a2031',ER:'#32251b',ECT:'#1d2834',S:'#1d2b21'};
const desc={D:'Sai do Terminal RU, cruza o campus, passa pela Via Direta e retorna ao RU pelo trecho de Reitoria e Educação Física.',I:'Faz o percurso complementar ao Direto, passando cedo por Reitoria e Via Direta antes de seguir por C&T, Geologia e setores.',ER:'Ligação expressa da Via Direta para a Reitoria.',ECT:'Ligação expressa da Via Direta para C&T / ECT.'};
const m=t=>{const[a,b]=t.split(':').map(Number);return a*60+b},now=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()},hh=v=>{v=(v+1440)%1440;return String(Math.floor(v/60)).padStart(2,'0')+':'+String(v%60).padStart(2,'0')};
const day=()=>{const d=new Date().getDay();return d===6?'saturday':d===0?'sunday':'weekday'},code=l=>l==='ECT'?'C&T':l,label=t=>t==='weekday'?'Dias úteis':t==='saturday'?'Sábado':'Domingo';
function nextTrip(arr,off=0){const n=now();for(let i=0;i<arr.length;i++){const base=m(arr[i]),pass=base+off;if(pass>=n)return{base,pass,index:i}}return null}
function segment(list,o,d){for(let a=0;a<list.length;a++){if(list[a][0]!==o)continue;for(let b=a+1;b<list.length;b++)if(list[b][0]===d)return{a,b}}return null}
function candidates(o,d){const service=day();if(service==='sunday')return[];const n=now(),out=[];Object.values(routes).forEach(r=>{if(r.day!==service)return;const s=segment(r.stops,o,d);if(!s)return;const arr=(schedule[r.terminal]||{})[r.line]||[];const trip=nextTrip(arr,r.stops[s.a][1]);if(!trip)return;const via=r.line==='D'?15:r.line==='I'?10:null;if(r.terminal==='ru'&&via!==null&&trip.index===arr.length-1&&r.stops[s.b][1]>via)return;const pass=trip.pass;out.push({r,line:r.line,pass,wait:pass-n,arrival:pass+r.stops[s.b][1]-r.stops[s.a][1],a:s.a,b:s.b})});const seen=new Set();return out.sort((a,b)=>a.arrival-b.arrival||a.wait-b.wait).filter(x=>{const k=x.line+'|'+x.pass+'|'+x.arrival;if(seen.has(k))return false;seen.add(k);return true})}
const wait=v=>v<=1?'agora':v<60?'em '+v+' min':'às '+hh(now()+v),origin=document.querySelector('#origin'),dest=document.querySelector('#dest');
Object.entries(stops).sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')).forEach(([id,n])=>{origin.add(new Option(n,id));dest.add(new Option(n,id))});
origin.value=localStorage.getItem('vdc-origin')&&stops[localStorage.getItem('vdc-origin')]?localStorage.getItem('vdc-origin'):'via';
dest.value=localStorage.getItem('vdc-dest')&&stops[localStorage.getItem('vdc-dest')]?localStorage.getItem('vdc-dest'):'rei';
function badgeClass(l){return l==='ER'?' er':''}
function setBestColor(box,l){box.style.setProperty('--best-color',colors[l]||'#f4dd19');box.style.setProperty('--best-soft',soft[l]||'#fff8d8');box.style.setProperty('--best-soft-dark',softDark[l]||'#2a2818')}
function serviceBadge(){const b=document.querySelector('#serviceBadge'),d=day(),w=new Intl.DateTimeFormat('pt-BR',{weekday:'long'}).format(new Date()).replace('-feira','');b.textContent=d==='weekday'?label(d)+' · '+w:label(d)}
function renderBest(){const o=origin.value,d=dest.value,box=document.querySelector('#bestCard'),route=document.querySelector('#routeCard');localStorage.setItem('vdc-origin',o);localStorage.setItem('vdc-dest',d);box.style.removeProperty('--best-color');box.style.removeProperty('--best-soft');box.style.removeProperty('--best-soft-dark');
if(o===d){box.innerHTML='<div class="best-top"><div><div class="result-kicker">Escolha dois locais diferentes</div><h3 class="result-title">Origem e destino estão iguais.</h3></div></div>';route.innerHTML='';return}
if(day()==='sunday'){box.innerHTML='<div class="best-top"><div><div class="result-kicker">Domingo</div><h3 class="result-title">Não há programação de domingo cadastrada.</h3><div class="route-name">Consulte abaixo os horários de dias úteis e sábado.</div></div></div>';route.innerHTML='';return}
const list=candidates(o,d);if(!list.length){box.innerHTML='<div class="best-top"><div><div class="result-kicker">Sem opção restante agora</div><h3 class="result-title">Não encontrei uma viagem programada para esse trajeto neste momento.</h3></div></div>';route.innerHTML='';return}
const b=list[0],alts=list.slice(1);setBestColor(box,b.line);let a='';alts.forEach((x,i)=>a+='<button class="alt-item" data-alt="'+i+'"><span class="alt-badge'+badgeClass(x.line)+'" style="--c:'+colors[x.line]+'">'+code(x.line)+'</span><span><b>'+names[x.line]+'</b><small>passagem ~ '+hh(x.pass)+' · toque para ver o trajeto</small></span><span class="alt-time">'+wait(x.wait)+'<small>chegada ~ '+hh(x.arrival)+'</small></span></button>');
box.innerHTML='<div class="best-top"><div><div class="result-kicker">Melhor opção estimada</div><div class="line-row"><span class="line-chip'+badgeClass(b.line)+'" style="--c:'+colors[b.line]+'">'+code(b.line)+'</span><div><h3 class="result-title">'+names[b.line]+'</h3><div class="route-name">'+stops[o]+' → '+stops[d]+'</div></div></div></div><div class="eta"><strong>'+wait(b.wait)+'</strong><span>passagem ~ '+hh(b.pass)+' · chegada ~ '+hh(b.arrival)+'</span></div></div><div class="action-row">'+(alts.length?'<button class="secondary" id="toggleAlt">Outras opções</button>':'')+'<a class="secondary" href="#horarios">Ver horários</a></div><div class="alternatives" id="alternatives">'+a+'</div>';
if(alts.length){const alt=document.querySelector('#alternatives'),btn=document.querySelector('#toggleAlt');btn.onclick=()=>{alt.classList.toggle('show');btn.textContent=alt.classList.contains('show')?'Ocultar opções':'Outras opções'};alt.querySelectorAll('[data-alt]').forEach(el=>el.onclick=()=>{const x=alts[+el.dataset.alt];renderRoute(x);document.querySelector('.route-section').scrollIntoView({behavior:'smooth',block:'start'})})}renderRoute(b)}
function renderRoute(b){const list=b.r.stops.slice(b.a,b.b+1),base=list[0][1],c=colors[b.line];document.querySelector('#routeCard').innerHTML='<div class="route-summary"><span class="line-chip'+badgeClass(b.line)+'" style="--c:'+c+'">'+code(b.line)+'</span><div><b>'+names[b.line]+'</b><span> · '+(list.length>2?(list.length-2)+' parada'+(list.length>3?'s':'')+' no caminho':'direto')+'</span></div></div><div class="timeline" style="--c:'+c+'">'+list.map((s,i)=>'<div class="stop '+((i===0||i===list.length-1)?'major':'')+'"><span class="node"></span><div><b>'+stops[s[0]]+'</b><small>'+(i===0?'embarque':i===list.length-1?'desembarque':'parada intermediária')+'</small></div><time>'+(i===0?hh(b.pass):'~ '+hh(b.pass+s[1]-base))+'</time></div>').join('')+'</div>'}
function renderDepartures(){const service=day(),box=document.querySelector('#departures'),ctx=document.querySelector('#departureContext');if(service==='sunday'){box.innerHTML='<div class="departure card departure-empty">Não há programação de domingo cadastrada.</div>';ctx.textContent='Sem programação cadastrada para domingo.';return}const terminal=service==='weekday'?'vd':'ru',lines=service==='weekday'?['D','I','ER','ECT']:['S'],rows=[];lines.forEach(l=>{const t=nextTrip((schedule[terminal]||{})[l]||[],0);if(t)rows.push({l,v:t.pass})});rows.sort((a,b)=>a.v-b.v);ctx.textContent=service==='weekday'?'Próximas saídas programadas da Via Direta.':'Próximas saídas programadas do Terminal RU.';box.innerHTML=rows.map(x=>'<div class="departure card" style="--c:'+colors[x.l]+'"><div class="code">'+code(x.l)+'</div><time>'+hh(x.v)+'</time><span>'+names[x.l]+'</span><small>'+(terminal==='vd'?'Via Direta':'Terminal RU')+'</small></div>').join('')||'<div class="departure card departure-empty">Sem novas saídas programadas hoje.</div>'}
function renderLines(){document.querySelector('#lineCards').innerHTML=['D','I','ER','ECT'].map(l=>'<article class="line-card card" style="--c:'+colors[l]+'"><div class="line-code">'+code(l)+'</div><h3>'+names[l]+'</h3><p>'+desc[l]+'</p><div class="line-note">'+(l==='ER'?'Via Direta → Reitoria':l==='ECT'?'Via Direta → C&T / ECT':'Percurso circular pelo Campus Central')+'</div></article>').join('')}
let schedDay=day()==='saturday'?'saturday':'weekday',schedLine=day()==='saturday'?'S':'D',schedTerminal=day()==='saturday'?'ru':'vd';
function renderDayTabs(){const box=document.querySelector('#dayTabs');box.innerHTML='';[['weekday','Dias úteis'],['saturday','Sábado']].forEach(([id,n])=>{const b=document.createElement('button');b.textContent=n;b.className=id===schedDay?'active':'';b.onclick=()=>{schedDay=id;schedLine=id==='weekday'?'D':'S';schedTerminal=id==='weekday'?'vd':'ru';renderSchedule()};box.appendChild(b)})}
function renderSchedule(){renderDayTabs();const tabs=document.querySelector('#scheduleTabs'),terms=document.querySelector('#terminalTabs'),grid=document.querySelector('#timesGrid'),scheduleBox=document.querySelector('.schedule'),ls=schedDay==='weekday'?['D','I','ER','ECT']:['S'];scheduleBox.style.setProperty('--schedule-color',colors[schedLine]);tabs.innerHTML='';ls.forEach(l=>{const b=document.createElement('button');b.textContent=code(l)+' · '+names[l];b.style.setProperty('--c',colors[l]);b.className=l===schedLine?'active':'';b.onclick=()=>{schedLine=l;schedTerminal=schedDay==='weekday'?'vd':'ru';renderSchedule()};tabs.appendChild(b)});terms.innerHTML='';const tt=schedDay==='weekday'&&['D','I'].includes(schedLine)?['vd','ru']:[schedDay==='weekday'?'vd':'ru'];tt.forEach(t=>{const b=document.createElement('button');b.textContent=t==='vd'?'Saída Via Direta':'Saída Terminal RU';b.style.setProperty('--c',colors[schedLine]);b.className=t===schedTerminal?'active':'';b.onclick=()=>{schedTerminal=t;renderSchedule()};terms.appendChild(b)});const arr=(schedule[schedTerminal]||{})[schedLine]||[],ni=day()===schedDay?arr.findIndex(t=>m(t)>=now()):-1;grid.innerHTML=arr.map((t,i)=>'<div class="time '+(i===ni?'next':'')+'">'+t+'</div>').join('')||'<div class="time time-empty">Sem horários cadastrados.</div>';document.querySelector('#scheduleStatus').textContent=schedDay==='weekday'?'Direto e Inverso conferidos · out/2026':'Sábado · horário de referência'}
document.querySelector('#findBtn').onclick=renderBest;origin.onchange=renderBest;dest.onchange=renderBest;document.querySelector('#swapBtn').onclick=()=>{const x=origin.value;origin.value=dest.value;dest.value=x;renderBest()};
const theme=document.querySelector('#themeToggle'),saved=localStorage.getItem('vai-de-circular-theme')||localStorage.getItem('vai-circular-theme');if(saved==='dark')document.body.classList.add('dark');const sync=()=>theme.textContent=document.body.classList.contains('dark')?'☀':'◐';theme.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('vai-de-circular-theme',document.body.classList.contains('dark')?'dark':'light');sync()};sync();
const top=document.querySelector('#toTop');addEventListener('scroll',()=>top.classList.toggle('show',scrollY>420),{passive:true});top.onclick=()=>scrollTo({top:0,behavior:'smooth'});
serviceBadge();renderLines();renderSchedule();renderBest();renderDepartures();setInterval(()=>{serviceBadge();renderBest();renderDepartures();renderSchedule()},60000);
})();